/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/addTaskScreen` | `/addTaskScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settingsScreen` | `/settingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tasksScreen` | `/tasksScreen`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/addTaskScreen` | `/addTaskScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settingsScreen` | `/settingsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tasksScreen` | `/tasksScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/addTaskScreen${`?${string}` | `#${string}` | ''}` | `/addTaskScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settingsScreen${`?${string}` | `#${string}` | ''}` | `/settingsScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tasksScreen${`?${string}` | `#${string}` | ''}` | `/tasksScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/addTaskScreen` | `/addTaskScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settingsScreen` | `/settingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tasksScreen` | `/tasksScreen`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
